-- Table: public.relations

-- DROP TABLE public.relations;

CREATE TABLE public.relations
(
  id integer NOT NULL DEFAULT nextval('relations_id_seq'::regclass),
  scaffoldinterface_id bigint,
  "having" character varying(50)
  "to" bigint,
  updated_at timestamp without time zone,
  created_at timestamp without time zone,
  deleted_at timestamp without time zone,
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.relations
  OWNER TO postgres;


INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_15_043043_services.php', '/var/www/html/test/app/Service.php', '/var/www/html/test/app/Http/Controllers/ServiceController.php', '/var/www/html/test/resources/views/service', 'services', '2017-02-15 16:30:43', '2017-02-15 16:30:43');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_15_090107_social_networks.php', '/var/www/html/test/app/Social_network.php', '/var/www/html/test/app/Http/Controllers/Social_networkController.php', '/var/www/html/test/resources/views/social_network', 'social_networks', '2017-02-15 21:01:07', '2017-02-15 21:01:07');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_15_090459_production_destinies.php', '/var/www/html/test/app/Production_destiny.php', '/var/www/html/test/app/Http/Controllers/Production_destinyController.php', '/var/www/html/test/resources/views/production_destiny', 'production_destinies', '2017-02-15 21:04:59', '2017-02-15 21:04:59');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_15_091239_water_sources.php', '/var/www/html/test/app/Water_source.php', '/var/www/html/test/app/Http/Controllers/Water_sourceController.php', '/var/www/html/test/resources/views/water_source', 'water_sources', '2017-02-15 21:12:39', '2017-02-15 21:12:39');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_023322_buildings.php', '/var/www/html/test/app/Building.php', '/var/www/html/test/app/Http/Controllers/BuildingController.php', '/var/www/html/test/resources/views/building', 'buildings', '2017-02-16 14:33:22', '2017-02-16 14:33:22');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_023405_transports.php', '/var/www/html/test/app/Transport.php', '/var/www/html/test/app/Http/Controllers/TransportController.php', '/var/www/html/test/resources/views/transport', 'transports', '2017-02-16 14:34:06', '2017-02-16 14:34:06');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_024156_facilities.php', '/var/www/html/test/app/Facility.php', '/var/www/html/test/app/Http/Controllers/FacilityController.php', '/var/www/html/test/resources/views/facility', 'facilities', '2017-02-16 14:41:56', '2017-02-16 14:41:56');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_024428_machineries.php', '/var/www/html/test/app/Machinery.php', '/var/www/html/test/app/Http/Controllers/MachineryController.php', '/var/www/html/test/resources/views/machinery', 'machineries', '2017-02-16 14:44:28', '2017-02-16 14:44:28');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_024735_institutes.php', '/var/www/html/test/app/Institute.php', '/var/www/html/test/app/Http/Controllers/InstituteController.php', '/var/www/html/test/resources/views/institute', 'institutes', '2017-02-16 14:47:35', '2017-02-16 14:47:35');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_024949_agricultural_roads.php', '/var/www/html/test/app/Agricultural_road.php', '/var/www/html/test/app/Http/Controllers/Agricultural_roadController.php', '/var/www/html/test/resources/views/agricultural_road', 'agricultural_roads', '2017-02-16 14:49:49', '2017-02-16 14:49:49');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_025012_problematics.php', '/var/www/html/test/app/Problematic.php', '/var/www/html/test/app/Http/Controllers/ProblematicController.php', '/var/www/html/test/resources/views/problematic', 'problematics', '2017-02-16 14:50:12', '2017-02-16 14:50:12');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_025053_type_document_earths.php', '/var/www/html/test/app/Type_document_earth.php', '/var/www/html/test/app/Http/Controllers/Type_document_earthController.php', '/var/www/html/test/resources/views/type_document_earth', 'type_document_earths', '2017-02-16 14:50:53', '2017-02-16 14:50:53');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_074509_production_units.php', '/var/www/html/test/app/Production_unit.php', '/var/www/html/test/app/Http/Controllers/Production_unitController.php', '/var/www/html/test/resources/views/production_unit', 'production_units', '2017-02-16 19:45:09', '2017-02-16 19:45:09');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_080904_indigenous_peoples.php', '/var/www/html/test/app/Indigenous_person.php', '/var/www/html/test/app/Http/Controllers/Indigenous_personController.php', '/var/www/html/test/resources/views/indigenous_person', 'indigenous_peoples', '2017-02-16 20:09:04', '2017-02-16 20:09:04');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_082234_popular_organizations.php', '/var/www/html/test/app/Popular_organization.php', '/var/www/html/test/app/Http/Controllers/Popular_organizationController.php', '/var/www/html/test/resources/views/popular_organization', 'popular_organizations', '2017-02-16 20:22:34', '2017-02-16 20:22:34');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_083015_appointments.php', '/var/www/html/test/app/Appointment.php', '/var/www/html/test/app/Http/Controllers/AppointmentController.php', '/var/www/html/test/resources/views/appointment', 'appointments', '2017-02-16 20:30:15', '2017-02-16 20:30:15');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_16_083058_person_people.php', '/var/www/html/test/app/Person_person.php', '/var/www/html/test/app/Http/Controllers/Person_personController.php', '/var/www/html/test/resources/views/person_person', 'person_people', '2017-02-16 20:30:58', '2017-02-16 20:30:58');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_17_023112_people.php', '/var/www/html/test/app/Person.php', '/var/www/html/test/app/Http/Controllers/PersonController.php', '/var/www/html/test/resources/views/person', 'people', '2017-02-17 14:31:12', '2017-02-17 14:31:12');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_17_025244_certifications.php', '/var/www/html/test/app/Certification.php', '/var/www/html/test/app/Http/Controllers/CertificationController.php', '/var/www/html/test/resources/views/certification', 'certifications', '2017-02-17 14:52:44', '2017-02-17 14:52:44');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_02_17_035239_type_identy_cards.php', '/var/www/html/test/app/Type_identy_card.php', '/var/www/html/test/app/Http/Controllers/Type_identy_cardController.php', '/var/www/html/test/resources/views/type_identy_card', 'type_identy_cards', '2017-02-17 15:52:39', '2017-02-17 15:52:39');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_03_17_022118_vegetable_sectors.php', '/var/www/html/test/app/Vegetable_sector.php', '/var/www/html/test/app/Http/Controllers/Vegetable_sectorController.php', '/var/www/html/test/resources/views/vegetable_sector', 'vegetable_sectors', '2017-03-17 14:21:18', '2017-03-17 14:21:18');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_03_17_022157_cycles.php', '/var/www/html/test/app/Cycle.php', '/var/www/html/test/app/Http/Controllers/CycleController.php', '/var/www/html/test/resources/views/cycle', 'cycles', '2017-03-17 14:21:57', '2017-03-17 14:21:57');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_03_17_024140_breeds.php', '/var/www/html/test/app/Breed.php', '/var/www/html/test/app/Http/Controllers/BreedController.php', '/var/www/html/test/resources/views/breed', 'breeds', '2017-03-17 14:41:40', '2017-03-17 14:41:40');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_03_17_024257_age_classes.php', '/var/www/html/test/app/Age_class.php', '/var/www/html/test/app/Http/Controllers/Age_classController.php', '/var/www/html/test/resources/views/age_class', 'age_classes', '2017-03-17 14:42:57', '2017-03-17 14:42:57');
INSERT INTO scaffoldinterfaces (package, migration, model, controller, views, tablename, created_at, updated_at) VALUES ('Laravel', '/var/www/html/test/database/migrations/2017_03_17_024327_commercializations.php', '/var/www/html/test/app/Commercialization.php', '/var/www/html/test/app/Http/Controllers/CommercializationController.php', '/var/www/html/test/resources/views/commercialization', 'commercializations', '2017-03-17 14:43:27', '2017-03-17 14:43:27');